#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XamarinTestApp.Droid.Resource", IsApplication=true)]

namespace XamarinTestApp.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int audioIcon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int blue_particle = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int green_particle = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int helloIcon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int red_particle = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int threeDIcon = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060005
			public const int apiResponse = 2131099653;
			
			// aapt resource value: 0x7f060001
			public const int btnPlayAudio = 2131099649;
			
			// aapt resource value: 0x7f060006
			public const int fragmentContainer = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int message = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int textView1 = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int textView4 = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int view1 = 2131099650;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AudioFragment = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int GraphicsFragment = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int HelloFragment = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int pug_pinball = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			// aapt resource value: 0x7f05000a
			public const int hello_api_label = 2131034122;
			
			// aapt resource value: 0x7f050008
			public const int title_activity_audio = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int title_activity_graphics = 2131034121;
			
			// aapt resource value: 0x7f050005
			public const int title_audio_play_mp3 = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int title_audio_playback = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int title_audio_record = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int title_dashboard = 2131034118;
			
			// aapt resource value: 0x7f050002
			public const int title_home = 2131034114;
			
			// aapt resource value: 0x7f050007
			public const int title_notifications = 2131034119;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
